name: Deploy Resumeblast to DigitalOcean Droplet

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'

            - name: Install dependencies (Frontend)
              run: npm ci

            - name: Build application
              run: |
                  npm run build

            - name: Create .env files
              run: |
                  echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" > .env
                  echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
                  echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env

                  echo "BASE_URL=${{ secrets.BASE_URL }}" > server/.env

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Set SSH key permissions
              run: chmod 600 $HOME/.ssh/id_rsa
            - name: Debug SSH key
              run: |
                  ls -la ~/.ssh
                  ssh-add -l
                  cat ~/.ssh/id_rsa.pub
            - name: Test SSH connection
              env:
                  DROPLET_IP: ${{ secrets.DROPLET_IP }}
              run: ssh -vvv azharie@$DROPLET_IP exit
            - name: Deploy to DigitalOcean Droplet
              env:
                  DROPLET_IP: ${{ secrets.DROPLET_IP }}
              run: |
                  set -e
                  rsync -avz --delete ./dist/ azharie@$DROPLET_IP:/var/www/deploy-service/sites/resume-blast || exit 1
                  rsync -avz --delete ./server/dist/ azharie@$DROPLET_IP:/var/www/deploy-service/sites/resume-blast/server || exit 1
                  rsync -avz .env azharie@$DROPLET_IP:/var/www/deploy-service/sites/resume-blast/ || exit 1
                  rsync -avz server/.env azharie@$DROPLET_IP:/var/www/deploy-service/sites/resume-blast/server/ || exit 1
                  ssh azharie@$DROPLET_IP "pm2 restart resume-blast" || exit 1
