name: Deploy ResumeBlast to DigitalOcean Droplet

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm ci

            - name: Build React app
              env:
                  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
                  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
                  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
              run: npm run build

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
                  if_key_exists: replace
                  config: |
                      Host *
                        StrictHostKeyChecking no

            - name: Deploy to DigitalOcean Droplet
              env:
                  DROPLET_IP: ${{ secrets.DROPLET_IP }}
              run: |
                  rsync -avz --delete ./dist/ root@$DROPLET_IP:/var/www/deploy-service/sites/resume-blast/
                  ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "sudo systemctl reload nginx"
